/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.siswa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Database.ConnectionHelper;
import Controller.tataUsahaController;
import Controller.siswaController;
import Interface.siswaInterface;
import Interface.tagihanInterface;
import Interface.tataUsahaInterface;
import Models.siswa;
import Models.tagihan;
import Models.tataUsaha;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class appSiswa extends javax.swing.JFrame {

    Connection a = ConnectionHelper.getConnection();

    List<siswa> record = new ArrayList<siswa>();
    siswaInterface sisServis;
    int row;

    /**
     * Creates new form
     */
    public appSiswa() {
        initComponents();

        sisServis = new siswaController();
    }

    void loadDataSis() {
        try {
            record = sisServis.getAll();
        } catch (SQLException ex) {
            Logger.getLogger(appAdmin.class.getName()).log(
                    Level.SEVERE, null, ex);
        }
    }

    void isiTextSis() {
        siswa sis = record.get(row);
        nisSiswaField.setText(sis.getNis());
        namaSiswaField.setText(sis.getNama());
        jurusanSiswaField.setText(sis.getJurusan());
        kelasSiswaField.setText(sis.getKelas());
    }

    void kosongkanTextSis() {
        nisSiswaField.setText("");
        namaSiswaField.setText("");
        jurusanSiswaField.setText("");
        kelasSiswaField.setText("");
    }

    void statusAwalSis() {
        kosongkanTextSis();
        loadDataSis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nisSiswaLabel = new javax.swing.JLabel();
        namaSiswaLabel = new javax.swing.JLabel();
        jurusanSiswaLabel = new javax.swing.JLabel();
        kelasSiswaLabel = new javax.swing.JLabel();
        nisSiswaField = new javax.swing.JTextField();
        namaSiswaField = new javax.swing.JTextField();
        jurusanSiswaField = new javax.swing.JTextField();
        kelasSiswaField = new javax.swing.JTextField();
        namaDisplayLabel = new javax.swing.JLabel();
        jurusanDisplayLabel = new javax.swing.JLabel();
        kelasDisplayLabel = new javax.swing.JLabel();
        nisDisplayLabel = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        nisSiswaDisplay = new javax.swing.JTextField();
        namaSiswaDisplay = new javax.swing.JTextField();
        jurusanSiswaDisplay = new javax.swing.JTextField();
        kelasSiswaDisplay = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        namaDisplayLabel1 = new javax.swing.JLabel();
        jurusanDisplayLabel1 = new javax.swing.JLabel();
        kelasDisplayLabel1 = new javax.swing.JLabel();
        nisDisplayLabel1 = new javax.swing.JLabel();
        nisSiswaDisplay1 = new javax.swing.JTextField();
        namaSiswaDisplay1 = new javax.swing.JTextField();
        jurusanSiswaDisplay1 = new javax.swing.JTextField();
        kelasSiswaDisplay1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tagihanSiswaDisplay = new javax.swing.JTextField();
        statusSiswaDisplay = new javax.swing.JTextField();
        Bayarbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("SISWA ");

        nisSiswaLabel.setText("NIS");

        namaSiswaLabel.setText("NAMA");

        jurusanSiswaLabel.setText("JURUSAN");

        kelasSiswaLabel.setText("KELAS  ");

        nisSiswaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisSiswaFieldActionPerformed(evt);
            }
        });

        namaDisplayLabel.setText("NAMA SISWA : ");

        jurusanDisplayLabel.setText("JURUSAN : ");

        kelasDisplayLabel.setText("KELAS : ");

        nisDisplayLabel.setText("NIS SISWA : ");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        nisSiswaDisplay.setEditable(false);
        nisSiswaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisSiswaDisplayActionPerformed(evt);
            }
        });

        namaSiswaDisplay.setEditable(false);
        namaSiswaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSiswaDisplayActionPerformed(evt);
            }
        });

        jurusanSiswaDisplay.setEditable(false);
        jurusanSiswaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanSiswaDisplayActionPerformed(evt);
            }
        });

        kelasSiswaDisplay.setEditable(false);
        kelasSiswaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasSiswaDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nisSiswaLabel)
                            .addComponent(namaSiswaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jurusanSiswaLabel)
                            .addComponent(namaDisplayLabel)
                            .addComponent(nisDisplayLabel)
                            .addComponent(jurusanDisplayLabel)
                            .addComponent(kelasDisplayLabel)
                            .addComponent(kelasSiswaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kelasSiswaDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nisSiswaField)
                                .addComponent(namaSiswaField)
                                .addComponent(jurusanSiswaField)
                                .addComponent(kelasSiswaField, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                                .addComponent(nisSiswaDisplay)
                                .addComponent(namaSiswaDisplay)
                                .addComponent(jurusanSiswaDisplay))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(submitBtn)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nisSiswaLabel)
                    .addComponent(nisSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSiswaLabel)
                    .addComponent(namaSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusanSiswaLabel)
                    .addComponent(jurusanSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasSiswaLabel)
                    .addComponent(kelasSiswaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nisDisplayLabel)
                    .addComponent(nisSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDisplayLabel)
                    .addComponent(namaSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusanDisplayLabel)
                    .addComponent(jurusanSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasDisplayLabel)
                    .addComponent(kelasSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        jTabbedPane1.addTab("ISI DATA SISWA", jPanel1);

        namaDisplayLabel1.setText("NAMA SISWA : ");

        jurusanDisplayLabel1.setText("JURUSAN : ");

        kelasDisplayLabel1.setText("KELAS : ");

        nisDisplayLabel1.setText("NIS SISWA : ");

        nisSiswaDisplay1.setEditable(false);
        nisSiswaDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisSiswaDisplay1ActionPerformed(evt);
            }
        });

        namaSiswaDisplay1.setEditable(false);
        namaSiswaDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSiswaDisplay1ActionPerformed(evt);
            }
        });

        jurusanSiswaDisplay1.setEditable(false);
        jurusanSiswaDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanSiswaDisplay1ActionPerformed(evt);
            }
        });

        kelasSiswaDisplay1.setEditable(false);
        kelasSiswaDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasSiswaDisplay1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tagihan : ");

        jLabel2.setText("Status : ");

        tagihanSiswaDisplay.setEditable(false);

        statusSiswaDisplay.setEditable(false);

        Bayarbtn.setText("Bayar");
        Bayarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nisDisplayLabel1)
                        .addComponent(namaDisplayLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jurusanDisplayLabel1)
                        .addComponent(kelasDisplayLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nisSiswaDisplay1)
                    .addComponent(namaSiswaDisplay1)
                    .addComponent(jurusanSiswaDisplay1)
                    .addComponent(kelasSiswaDisplay1)
                    .addComponent(tagihanSiswaDisplay)
                    .addComponent(statusSiswaDisplay))
                .addGap(101, 101, 101))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(Bayarbtn)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nisDisplayLabel1)
                    .addComponent(nisSiswaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaDisplayLabel1)
                    .addComponent(namaSiswaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusanDisplayLabel1)
                    .addComponent(jurusanSiswaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasDisplayLabel1)
                    .addComponent(kelasSiswaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tagihanSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(statusSiswaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(Bayarbtn)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BAYAR SPP", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nisSiswaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisSiswaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisSiswaFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String nis = nisSiswaField.getText().toString().trim();
        String nama = namaSiswaField.getText().toString().trim();
        String jurusan = jurusanSiswaField.getText().toString().trim();
        String kelas = kelasSiswaField.getText().toString().trim();

        if (nis.equals("") || nama.equals("") || jurusan.equals("") || kelas.equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong semua data diisi");
        } else {
            try {
                siswa sis = new siswa(null, null, null, null, null, null);
                sis.setNis(nisSiswaField.getText());
                sis.setNama(namaSiswaField.getText());
                sis.setJurusan(jurusanSiswaField.getText());
                sis.setKelas(kelasSiswaField.getText());
                sis.setJumlah("250.000");
                sis.setStatus("Belum Lunas");
                sisServis.insert(sis);
                nisSiswaField.disable();
                namaSiswaField.disable();
                jurusanSiswaField.disable();
                kelasSiswaField.disable();
                nisSiswaDisplay.setText(nisSiswaField.getText());
                namaSiswaDisplay.setText(namaSiswaField.getText());
                jurusanSiswaDisplay.setText(jurusanSiswaField.getText());
                kelasSiswaDisplay.setText(kelasSiswaField.getText());
                submitBtn.disable();

                nisSiswaDisplay1.setText(nisSiswaField.getText());
                namaSiswaDisplay1.setText(namaSiswaField.getText());
                jurusanSiswaDisplay1.setText(jurusanSiswaField.getText());
                kelasSiswaDisplay1.setText(kelasSiswaField.getText());
                tagihanSiswaDisplay.setText("250.000");
                statusSiswaDisplay.setText("Belum Lunas");
                this.statusAwalSis();

                JOptionPane.showMessageDialog(this, "Data Tersimpan");
            } catch (SQLException ex) {
                Logger.getLogger(appAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void nisSiswaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisSiswaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisSiswaDisplayActionPerformed

    private void namaSiswaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSiswaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSiswaDisplayActionPerformed

    private void jurusanSiswaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanSiswaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanSiswaDisplayActionPerformed

    private void kelasSiswaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasSiswaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasSiswaDisplayActionPerformed

    private void nisSiswaDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisSiswaDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisSiswaDisplay1ActionPerformed

    private void namaSiswaDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSiswaDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSiswaDisplay1ActionPerformed

    private void jurusanSiswaDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanSiswaDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanSiswaDisplay1ActionPerformed

    private void kelasSiswaDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasSiswaDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasSiswaDisplay1ActionPerformed

    private void BayarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarbtnActionPerformed
        String nis = nisSiswaDisplay1.getText().toString().trim();
        String nama = namaSiswaDisplay1.getText().toString().trim();
        String jurusan = jurusanSiswaDisplay1.getText().toString().trim();
        String kelas = kelasSiswaDisplay1.getText().toString().trim();
        String jumlah = tagihanSiswaDisplay.getText().toString().trim();
        String status = statusSiswaDisplay.getText().toString().trim();

        if (nis.equals("") || nama.equals("") || jurusan.equals("") || kelas.equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak ada data");
        } else {
            try {
                siswa sis = new siswa(null, null, null, null, null, null);

                nis = nisSiswaDisplay.getText();
                sisServis.delete(nis);

                sis.setNis(nisSiswaDisplay.getText());
                sis.setNama(namaSiswaDisplay.getText());
                sis.setJurusan(jurusanSiswaDisplay.getText());
                sis.setKelas(kelasSiswaDisplay.getText());
                sis.setJumlah("0");
                sis.setStatus("Lunas");
                sisServis.insert(sis);
                nisSiswaDisplay1.setText(nisSiswaDisplay.getText());
                namaSiswaDisplay1.setText(namaSiswaDisplay.getText());
                jurusanSiswaDisplay1.setText(jurusanSiswaDisplay.getText());
                kelasSiswaDisplay1.setText(kelasSiswaDisplay.getText());
                tagihanSiswaDisplay.setText("0");
                statusSiswaDisplay.setText("Lunas");
                this.statusAwalSis();
                JOptionPane.showMessageDialog(this, "Tagihanmu Lunas !");
            } catch (SQLException ex) {
                Logger.getLogger(appAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BayarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bayarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jurusanDisplayLabel;
    private javax.swing.JLabel jurusanDisplayLabel1;
    private javax.swing.JTextField jurusanSiswaDisplay;
    private javax.swing.JTextField jurusanSiswaDisplay1;
    private javax.swing.JTextField jurusanSiswaField;
    private javax.swing.JLabel jurusanSiswaLabel;
    private javax.swing.JLabel kelasDisplayLabel;
    private javax.swing.JLabel kelasDisplayLabel1;
    private javax.swing.JTextField kelasSiswaDisplay;
    private javax.swing.JTextField kelasSiswaDisplay1;
    private javax.swing.JTextField kelasSiswaField;
    private javax.swing.JLabel kelasSiswaLabel;
    private javax.swing.JLabel namaDisplayLabel;
    private javax.swing.JLabel namaDisplayLabel1;
    private javax.swing.JTextField namaSiswaDisplay;
    private javax.swing.JTextField namaSiswaDisplay1;
    private javax.swing.JTextField namaSiswaField;
    private javax.swing.JLabel namaSiswaLabel;
    private javax.swing.JLabel nisDisplayLabel;
    private javax.swing.JLabel nisDisplayLabel1;
    private javax.swing.JTextField nisSiswaDisplay;
    private javax.swing.JTextField nisSiswaDisplay1;
    private javax.swing.JTextField nisSiswaField;
    private javax.swing.JLabel nisSiswaLabel;
    private javax.swing.JTextField statusSiswaDisplay;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField tagihanSiswaDisplay;
    // End of variables declaration//GEN-END:variables
}
